line 2 "top.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 9 "top.tlv" 1
//_\SV
   // Macro providing required top-level module definition, random
   // stimulus support, and Verilator config.
   `include "sqrt32.v" 
   module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */   // (Expanded in Nav-TLV pane.)
`include "top_gen.sv" //_\TLV
   assign L0_reset_a0 = reset;

   //...
   //_|calc
      //_@1
         assign CALC_aa_sq_a1[31:0] = CALC_aa_a1[3:0] * CALC_aa_a1[3:0];
         assign CALC_bb_sq_a1[31:0] = CALC_bb_a1[3:0] * CALC_bb_a1[3:0];
      //_@2
         assign CALC_cc_sq_a2[31:0] = CALC_aa_sq_a2 + CALC_bb_sq_a2;
      //_@3
         assign CALC_cc_a3[31:0] = sqrt(CALC_cc_sq_a3);
        

   // Assert these to end simulation (before Makerchip cycle limit).
   assign passed = cyc_cnt > 40;
   assign failed = 1'b0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper (in "top_gen.sv").
`undef BOGUS_USE
